---
abstract: 'Mojolicious plugin for blog integration'
author:
  - 'Adam Stokes <hackr@cypherbook.com>'
build_requires:
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Blog
requires:
  DBIx::ResultSet: 0
  Data::Dump: 0
  File::Basename: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  Mojo::Base: 0
  Path::Tiny: 0
  perl: v5.16.0
  strictures: 1
resources:
  homepage: https://github.com/battlemidget/Mojolicious-Plugin-Blog
  repository: https://github.com/battlemidget/Mojolicious-Plugin-Blog.git
version: 0.003
